### ISSUE TITLE
[Dark] Pause line highlight should be more noticeable

### ISSUE THREAD

**Issue by jasonLaster** [replayio/design#34]
The pause line in dark mode is a bit too subtle. Also, not sure if the "flash" is noticeable in dark mode.
![image](https://user-images.githubusercontent.com/254562/164980402-e8fcf02c-6444-4208-83de-838cfe457493.png)

https://discord.com/channels/779097926135054346/957390059714281482/967760989095350272

**Comment by Andarist** [comment]
This would definitely improve the situation - but i wonder: is there a strong argument here to **avoid** the scroll jump in the reported scenario?

**Comment by jonbell-lot23** [comment]
Agreed. There's a key insight here:

* It's hard to see what changed

And three implantation ideas:

1. More noticeable flash
2. More clear background colour
3. Scroll jump

I'd argue the first two are less impactful than the third, and can all work together. Is there an argument against the scroll jump?

**Comment by jasonLaster** [comment]
re scroll jump: I think i need to see a video of the scroll jump we're referring to.  If i'm understanding correctly though, the reason is that if you scroll every time you step forward or backwards it would be disruptive. Step in / out is different, but harder to differentiate from.

**Comment by Andarist** [comment]
Yes, scrolling at all times would be disruptive - im specifically mentioning a scenario when we cross a function boundary though. When I either jump into a new function or jump out of the existing ones. In this scenario I usually have no idea where the "target" function is and I dont expect my scroll position to be preserved because most often than not it's not preserved as very often the target function is elsewhere

**Comment by gideonred** [comment]
This ticket has been moved to [DES-26](https://linear.app/replay/issue/DES-26/[dark]-pause-line-highlight-should-be-more-noticeable)
