### ISSUE TITLE
Improve support for print statements with 200+ messages

### ISSUE THREAD

**Issue by jasonLaster** [replayio/design#36]
### Discussed in https://github.com/RecordReplay/devtools/discussions/6531

<div type='discussions-op-text'>

<sup>Originally posted by **jasonLaster** April 22, 2022</sup>
It would be nice to explore ways in which our frontend can support situations where there are more than 200 messages to show in the console. Here are some examples:

1. Adding print statement that has 200+ messages
2. Showing 200+ exceptions 
3. Showing 200+ Mouse Move events

---

In the Print Statement panel we currently try to show up to 500 messages, but we do not let you edit the expression if there are more than 200.

In the Console Filter bar, we currently default to disabling event listeners if there are more than 200, but I don't think we disable exceptions.

---

Our Analysis API supports an `addPoints` call which allows the frontend to specify the points to analyze and gives the frontend a lot of latitude for deciding how the UX should work.</div>

**Comment by jasonLaster** [comment]
~~https://www.loom.com/share/30fa87c4df414d989d8d8c1a420e2e12~~
https://www.loom.com/share/0f312f647134441f955a107dc14ae631
some figma graphics 
https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/Replay-Design-Doc?node-id=11491%3A103519

**Comment by jasonLaster** [comment]
* perhaps show markers from outside of the focus region
* perhaps focus from within the timeline

**Comment by jonbell-lot23** [comment]
Here was my original design ticket on this: https://github.com/RecordReplay/design/issues/25

Similar but not the exact same task. Mine is more on the design side, this is a more general frontend task.

**Comment by jaril** [comment]
This is in the current sprint but as far as I know isn't being actively worked on. I'm also not clear on what the next steps are here since things might have shifted since the original filing.

I _think_ we're still working on fundamental analyses/focus changes but we're nearing the end of the tunnel there. Loosening some of the restrictions (e.g. <200) that we have here seems like an obvious next step if we're focused on making sure people aren't kept from debugging effectively.

@jcmorrow you've been referencing this a bit and you're the resident expert on analyses now. Are you already working on this/any thoughts on how we should proceed? My gut feeling is let's pick it up next sprint after we have a better idea of what the remaining analysis/focus changes means for how we should design this.

**Comment by jcmorrow** [comment]
we now show up to 1000 points, which helps a little?

**Comment by jcmorrow** [comment]
Also - you can use the console points to set being and end now, which is nice.

**Comment by jcmorrow** [comment]
one of the things I have struggled with with this card is that we don't really have specifics on what we want to do yet

**Comment by jonbell-lot23** [comment]
When this happens, I typically propose a new issue that is more specific/defined.

**Comment by jaril** [comment]
I'll take a stab at clarifying this next sprint, and then figuring out what needs to be worked on/when it should be worked on.

**Comment by gideonred** [comment]
This ticket has been moved to [DES-27](https://linear.app/replay/issue/DES-27/improve-support-for-print-statements-with-200-messages)
